obj-$(CONFIG_EXYNOS_DECON_LCD_S6E8AA0)	+= s6e8aa0_mipi_lcd.o s6e8aa0_lcd_ctrl.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E8AA5X01)	+= s6e8aa5x01_mipi_lcd.o s6e8aa5x01_lcd_ctrl.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E36W1X01)	+= s6e36w1x01_mipi_lcd.o s6e36w1x01_lcd_ctrl.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3AA2)	+= s6e3aa2_mipi_lcd.o s6e3aa2_lcd_ctrl.o
